export const strings = {
    en: {
        // Common
        search: "Search",
        search_placeholder: "Search categories or products...",
        all_categories: "All Categories",
        explore_categories: "Explore Categories",
        fresh_arrivals: "Fresh Arrivals",
        see_all: "See all",
        see_more: "See more",
        add: "ADD",
        out_of_stock: "Out of Stock",
        loading: "Loading...",
        items: "items",
        gram: "g",
        kg: "kg",
        pkt: "pkt",
        dozen: "dozen",

        // Tab Bar
        home: "Home",
        categories: "Categories",
        orders: "Orders",
        profile: "Profile",

        // Profile Screen
        my_profile: "My Profile",
        personal_info: "Personal Information",
        app_settings: "App Settings",
        language: "Language",
        select_language: "Select Language",
        switch_shopkeeper: "Switch to Shopkeeper",
        logout: "Logout",
        help_support: "Help & Support",
        privacy_policy: "Privacy Policy",
        balance: "Balance",
        delete_account: "Delete Account",
        delete_account_confirm: "Are you sure you want to delete your account? This action cannot be undone.",

        // Cart & Checkout
        my_cart: "My Cart",
        checkout: "Checkout",
        total: "Total",
        place_order: "Place Order",
        order_success: "Order Placed Successfully!",

        // Product Details
        quantity: "Quantity",
        description: "Description",
        related_products: "Related Products",
        product_details: "Product Details",
        offer: "OFFER",
        product_desc_fallback: "Fresh and high quality products delivered directly to your doorstep. Verified by local farmers.",
        "30_min": "30 Min",
        easy_return: "Easy Return",
        add_to_cart: "Add to Cart",
        weight_g: "Weight (g)",
        price_rs: "Price (₹)",

        // Stock Status
        fresh: "Fresh",
        packet: "Packet",
        shop_online: "Online",
        shop_offline: "Offline",
        show_shop_to_customers: "Show Shop to Customers",

        // Auth
        welcome_back: "Welcome Back!",
        login_desc: "Log in to continue your fresh shopping.",
        select_shop: "Select Shop",
        select_shop_desc: 'Please select a shop to continue shopping.',
        register_shop: 'Register Your Shop',
        register_shop_desc: 'Setting up your digital storefront only takes a minute.',
        select_lang: 'Select Preferred Language',
        add_shop_image: 'Add Shop Image (Optional)',
        change_image: 'Change Image',
        shop_name: 'Shop Name',
        shop_name_placeholder: 'e.g. Jai Malhar Store',
        shop_address: 'Shop Address',
        shop_address_placeholder: 'Enter full address',
        fetch_location: 'Use Live Location',
        create_store: 'Create My Store',
        phone_number: "Phone Number",
        phone_placeholder: "Enter your phone (e.g. 9876543210)",
        password_placeholder: "••••••••",
        logging_in: "Logging in...",
        no_account: "Don't have an account?",
        signup: "Sign Up",
        login: "Login",
        join_fresh_club: "Join the Fresh Club",
        signup_desc: "Get fresh groceries delivered to your door in minutes.",
        full_name: "Full Name",
        name_placeholder: "Kinjal Gawali",
        creating_account: "Creating Account...",
        create_account: "Create Account",
        already_have_account: "Already have an account?",
        by_signing_up: "By signing up, you agree to our",
        terms_service: "Terms of Service",
        and: "and",
        i_am_a: "I am a...",
        customer: "Customer",
        shopkeeper: "Shopkeeper",

        // Onboarding
        onboard_title_1: "Welcome",
        onboard_desc_1: "Your daily essentials, delivered fresh from your trusted local Kirana store.",
        onboard_title_2: "Organic Pulses",
        onboard_desc_2: "High-quality Toor, Moong, and Masoor Dal sourced directly for your family.",
        onboard_title_3: "Fresh Vegetables",
        onboard_desc_3: "Farm-fresh onions, potatoes, and tomatoes. Handpicked daily.",
        onboard_title_4: "Authentic Spices",
        onboard_desc_4: "Pure Haldi, Mirchi, and Dhania to bring the real taste of India to your kitchen.",

        // Orders
        my_orders: "My Orders",
        no_orders: "You haven't placed any orders yet.",
        pending: "Pending",
        delivered: "Delivered",
        cancelled: "Cancelled",

        // Cart Empty
        cart_empty: "Your cart is empty",
        start_shopping: "Start Shopping",
        clear: "Clear",
        subtotal: "Subtotal",
        proceed_to_buy: "Proceed to Buy",
        placing_order: "Placing Order...",

        // Home Sections
        daily_use: "Daily Use",
        chai_nashta: "Chai & Nashta",
        spices_pulses: "Spices & Pulses",
        household: "Cleaning & Household",
        pickup_from: "Pickup From",

        // Showcase Items
        soft_drinks: "Soft Drinks",
        spices: "Spices",
        cleaning: "Cleaning",
        baby_care: "Baby Care",

        // Showcase Subtitles
        cool_fizzy: "Cool & Fizzy",
        authentic_taste: "Authentic Taste",
        essentials: "Essentials",
        gentle_safe: "Gentle & Safe",

        // Showcase Tags
        upto_20_off: "UPTO 20% OFF",
        fresh_tag: "Fresh",
        best_seller: "Best Seller",
        trusted: "Trusted",

        // Extras
        unit: "unit",
        products: "Products",

        // Shopkeeper Common
        inventory: "Inventory",
        shop_orders: "Shop Orders",
        credit: "Credit",
        revenue: "Revenue",
        shop_performance: "Shop Performance",
        management: "Management",

        // Shopkeeper Profile
        shopkeeper_profile: "Shopkeeper Profile",
        shop_owner: "Shop Owner",
        no_phone: "No phone linked",
        store_settings: "Store Settings",
        notifications: "Push Notifications",
        support_faq: "Support & FAQ",
        switch_customer: "Switch to Customer",
        browse_as_user: "Browse products as user",
        shop_panel_v1: "Shop Panel v1.0.0",

        // Inventory
        weight_based: "Weight Based",
        packet_based: "Packet Based",
        no_categories: "No categories yet",
        tap_to_add_category: "Tap + to add your first one",
        delete_category: "Delete Category",
        delete_category_confirm: "Delete this category and all its products?",
        all_orders: "All Orders",
        open: "Open",
        completed: "Completed",
        add_to_credit: "Add to Credit",
        mark_packed: "Mark Packed",
        ledger_updated: "Ledger updated successfully",
        added_to_credit: "Added to Credit!",
        credit_khata: "Credit / Khata",
        total_due: "Total Due",
        add_customer: "Add New Customer",
        customer_name: "Customer Name",
        initial_amount: "Initial Amount (₹)",
        due: "Due",
        hidden: "HIDDEN",
        live: "Live",
        off: "Off",
        selling_price: "SELLING PRICE (₹)",
        current_stock: "CURRENT STOCK",
        no_products: "No products yet",
        tap_to_add_product: "Tap + to add your first product",
        add_featured: "Add to Fresh Arrivals",
        remove_featured: "Remove from Fresh Arrivals",
        new_category: "New Category",
        choose_icon: "Choose Application Icon",
        upload_custom: "OR UPLOAD CUSTOM",
        upload_gallery: "Upload from Gallery",
        category_name_label: "Category Name",
        how_to_sell: "Category Type (How to sell?)",
        weight_based_title: "Weight Based",
        item_based_title: "Item Based",
        create_category_btn: "Create Category",
        add_item: "Add Item",
        tap_add_photo: "Tap to Add Photo",
        product_name_label: "Product Name",
        subtitle_optional: "Subtitle (Optional)",
        price_label: "Price (₹)",
        stock_label: "Stock",
        show_in_featured: "Show in Fresh Arrivals?",
        featured_sub: "Items will appear in the top section of Home Screen.",
        save_product: "Save Product",
    },
    hi: {
        // Common
        search: "खोजें",
        search_placeholder: "श्रेणी या उत्पाद खोजें...",
        all_categories: "सभी श्रेणियां",
        explore_categories: "श्रेणियां देखें",
        fresh_arrivals: "ताज़ा सामान",
        see_all: "सब देखें",
        see_more: "और देखें",
        add: "जोड़ें",
        out_of_stock: "स्टॉक खत्म",
        loading: "लोड हो रहा है...",
        items: "सामान",
        gram: "ग्राम",
        kg: "किलो",
        pkt: "पैकेट",
        dozen: "दर्जन",

        // Tab Bar
        home: "होम",
        categories: "श्रेणियां",
        orders: "ऑर्डर",
        profile: "प्रोफ़ाइल",

        // Profile Screen
        my_profile: "मेरी प्रोफ़ाइल",
        personal_info: "व्यक्तिगत जानकारी",
        app_settings: "एप्प सेटिंग्स",
        language: "भाषा",
        select_language: "भाषा चुनें",
        switch_shopkeeper: "दुकानदार मोड",
        logout: "लॉग आउट",
        help_support: "सहायता",
        privacy_policy: "गोपनीयता नीति",
        balance: "बाकी",
        delete_account: "खाता हटाएं",
        delete_account_confirm: "क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया वापस नहीं ली जा सकती।",

        // Cart & Checkout
        my_cart: "मेरी टोकरी",
        checkout: "चेकआउट",
        total: "कुल",
        place_order: "ऑर्डर दें",
        order_success: "ऑर्डर सफल रहा!",

        // Product Details
        quantity: "मात्रा",
        description: "विवरण",
        related_products: "संबंधित उत्पाद",
        product_details: "उत्पाद का विवरण",
        offer: "ऑफर",
        product_desc_fallback: "ताजा और उच्च गुणवत्ता वाले उत्पाद सीधे आपके दरवाजे पर पहुँचाए जाते हैं। स्थानीय किसानों द्वारा सत्यापित।",
        "30_min": "30 मिनट",
        easy_return: "आसान वापसी",
        add_to_cart: "कार्ट में जोड़ें",
        weight_g: "वजन (ग्राम)",
        price_rs: "कीमत (₹)",

        // Stock Status
        fresh: "ताज़ा",
        packet: "पैकेट",
        shop_online: "ऑनलाइन",
        shop_offline: "ऑफलाइन",
        show_shop_to_customers: "ग्राहकों को दुकान दिखाएं",

        // Auth
        login_desc: "अपनी ताज़ा खरीदारी जारी रखने के लिए लॉग इन करें।",
        select_shop: "दुकान चुनें",
        select_shop_desc: 'खरीदारी जारी रखने के लिए कृपया एक दुकान चुनें।',
        register_shop: 'अपनी दुकान रजिस्टर करें',
        register_shop_desc: 'अपनी डिजिटल दुकान सेटअप करने में बस एक मिनट लगता है।',
        select_lang: 'अपनी पसंदीदा भाषा चुनें',
        add_shop_image: 'दुकान की फोटो जोड़ें (वैकल्पिक)',
        change_image: 'फोटो बदलें',
        shop_name: 'दुकान का नाम',
        shop_name_placeholder: 'जैसे. जय मल्हार स्टोर',
        shop_address: 'दुकान का पता',
        shop_address_placeholder: 'पूरा पता दर्ज करें',
        fetch_location: 'लाइव लोकेशन का उपयोग करें',
        create_store: 'मेरी दुकान बनाएं',
        phone_number: "फ़ोन नंबर",
        phone_placeholder: "अपना फोन नंबर डालें (जैसे 9876543210)",
        password_placeholder: "अपना पासवर्ड डालें",
        logging_in: "लॉग इन हो रहा है...",
        no_account: "खाता नहीं है?",
        signup: "साइन अप करें",
        login: "लॉग इन",
        join_fresh_club: "फ्रेश क्लब से जुड़ें",
        signup_desc: "ताज़ा किराने का सामान कुछ ही मिनटों में अपने घर पर पाएं।",
        full_name: "पूरा नाम",
        name_placeholder: "अपना नाम डालें",
        creating_account: "खाता बनाया जा रहा है...",
        create_account: "खाता बनाएं",
        already_have_account: "पहले से ही खाता है?",
        by_signing_up: "साइन अप करके, आप हमारी",
        terms_service: "सेवा की शर्तों",
        and: "और",
        i_am_a: "मैं हूँ एक...",
        customer: "ग्राहक",
        shopkeeper: "दुकानदार",

        // Onboarding
        onboard_title_1: "स्वागत है",
        onboard_desc_1: "आपकी दैनिक ज़रूरतें, आपके भरोसेमंद स्थानीय किराना स्टोर से ताज़ा।",
        onboard_title_2: "जैविक दालें",
        onboard_desc_2: "आपके परिवार के लिए सीधे स्रोत से उच्च गुणवत्ता वाली तूर, मूंग और मसूर दाल।",
        onboard_title_3: "ताज़ा सब्जियाँ",
        onboard_desc_3: "खेत-ताज़ा प्याज, आलू और टमाटर। रोज़ाना हाथ से चुने गए।",
        onboard_title_4: "प्रामाणिक मसाले",
        onboard_desc_4: "आपकी रसोई में भारत का असली स्वाद लाने के लिए शुद्ध हल्दी, मिर्ची और धनिया।",

        // Orders
        my_orders: "मेरे ऑर्डर",
        no_orders: "आपने अभी तक कोई ऑर्डर नहीं दिया है।",
        pending: "लंबित",
        delivered: "पहुंचा दिया गया",
        cancelled: "रद्द",

        // Cart Empty
        cart_empty: "आपकी टोकरी खाली है",
        start_shopping: "खरीदारी शुरू करें",
        clear: "साफ करें",
        subtotal: "उप-कुल",
        proceed_to_buy: "खरीदने के लिए आगे बढ़ें",
        placing_order: "ऑर्डर दिया जा रहा है...",

        // Home Sections
        daily_use: "दैनिक उपयोग",
        chai_nashta: "चाय और नाश्ता",
        spices_pulses: "मसाले और दालें",
        household: "सफाई और घरेलू",
        pickup_from: "यहाँ से उठाएं",

        // Showcase Items
        soft_drinks: "कोल्ड ड्रिंक्स",
        spices: "मसाले",
        cleaning: "सफाई",
        baby_care: "बेबी केयर",

        // Showcase Subtitles
        cool_fizzy: "ठंडा और ताज़ा",
        authentic_taste: "असली स्वाद",
        essentials: "ज़रूरी सामान",
        gentle_safe: "कोमल और सुरक्षित",

        // Showcase Tags
        upto_20_off: "20% तक की छूट",
        fresh_tag: "ताज़ा",
        best_seller: "सबसे ज़्यादा बिकने वाला",
        trusted: "भरोसेमंद",

        // Extras
        unit: "नग",
        products: "उत्पाद",

        // Shopkeeper Common
        inventory: "इन्वेंटरी",
        shop_orders: "दुकान के ऑर्डर",
        credit: "उधारी",
        revenue: "कुल कमाई",
        shop_performance: "दुकान का प्रदर्शन",
        management: "प्रबंधन",

        // Shopkeeper Profile
        shopkeeper_profile: "दुकानदार प्रोफ़ाइल",
        shop_owner: "दुकान के मालिक",
        no_phone: "कोई फोन लिंक नहीं",
        store_settings: "दुकान की सेटिंग्स",
        notifications: "सूचनाएं",
        support_faq: "सहायता और प्रश्न",
        switch_customer: "ग्राहक मोड",
        browse_as_user: "ग्राहक के तौर पर देखें",
        shop_panel_v1: "दुकान पैनल v1.0.0",

        // Inventory
        weight_based: "वजन आधारित",
        packet_based: "पैकेट आधारित",
        no_categories: "अभी कोई श्रेणी नहीं है",
        tap_to_add_category: "पहली श्रेणी जोड़ने के लिए + दबाएं",
        delete_category: "श्रेणी हटाएं",
        delete_category_confirm: "क्या आप इस श्रेणी और इसके सभी उत्पादों को हटाना चाहते हैं?",
        all_orders: "सभी ऑर्डर",
        open: "खुला",
        completed: "पूरा हुआ",
        add_to_credit: "उधारी में जोड़ें",
        mark_packed: "पैक किया गया",
        ledger_updated: "लेजर सफलतापूर्वक अपडेट किया गया",
        added_to_credit: "उधारी में जोड़ा गया!",
        credit_khata: "उधारी / खाता",
        total_due: "कुल उधारी",
        add_customer: "नया ग्राहक जोड़ें",
        customer_name: "ग्राहक का नाम",
        initial_amount: "शुरुआती राशि (₹)",
        due: "बाकी",
        hidden: "छिपा हुआ",
        live: "चालू",
        off: "बंद",
        selling_price: "बिक्री मूल्य (₹)",
        current_stock: "मौजूद स्टॉक",
        no_products: "अभी कोई उत्पाद नहीं है",
        tap_to_add_product: "पहला उत्पाद जोड़ने के लिए + दबाएं",
        add_featured: "ताजा आगमन में जोड़ें",
        remove_featured: "ताजा आगमन से हटाएं",
        new_category: "नई कैटेगरी",
        choose_icon: "एप्लिकेशन आइकन चुनें",
        upload_custom: "या खुद का फोटो लोड करें",
        upload_gallery: "गैलरी से अपलोड करें",
        category_name_label: "कैटेगरी का नाम",
        how_to_sell: "कैटेगरी का प्रकार (कैसे बेचें?)",
        weight_based_title: "वजन के अनुसार",
        item_based_title: "नग के अनुसार",
        create_category_btn: "कैटेगरी बनाएं",
        add_item: "नया आइटम जोड़ें",
        tap_add_photo: "फोटो जोड़ने के लिए छुएं",
        product_name_label: "उत्पाद का नाम",
        subtitle_optional: "उप-शीर्षक (वैकल्पिक)",
        price_label: "कीमत (₹)",
        stock_label: "स्टॉक",
        show_in_featured: "ताजा आगमन में दिखाएं?",
        featured_sub: "आइटम होम स्क्रीन के सबसे ऊपरी हिस्से में दिखेंगे।",
        save_product: "उत्पाद सुरक्षित करें",
    },
    mr: {
        // Common
        search: "शोधा",
        search_placeholder: "श्रेणी किंवा उत्पादन शोधा...",
        all_categories: "सर्व श्रेणी",
        explore_categories: "श्रेणी पहा",
        fresh_arrivals: "ताज्या वस्तू",
        see_all: "सर्व पहा",
        see_more: "अधिक पहा",
        add: "निवडा",
        out_of_stock: "स्टॉक संपला",
        loading: "लोड होत आहे...",
        items: "वस्तू",
        gram: "ग्रॅम",
        kg: "किलो",
        pkt: "पॅकेट",
        dozen: "डझन",

        // Tab Bar
        home: "होम",
        categories: "श्रेणी",
        orders: "ऑर्डर",
        profile: "प्रोफाईल",

        // Profile Screen
        my_profile: "माझी प्रोफाईल",
        personal_info: "वैयक्तिक माहिती",
        app_settings: "अॅप सेटिंग्ज",
        language: "भाषा",
        select_language: "भाषा निवडा",
        switch_shopkeeper: "दुकानदार मोड",
        logout: "लॉग आउट",
        help_support: "मदत",
        privacy_policy: "गोपनीयता धोरण",
        balance: "शिल्लक",
        delete_account: "खाते हटवा",
        delete_account_confirm: "तुम्ही नक्की तुमचे खाते हटवू इच्छिता? ही कृती परत करता येणार नाही.",

        // Cart & Checkout
        my_cart: "माझी पिशवी",
        checkout: "चेकआउट",
        total: "एकूण",
        place_order: "ऑर्डर द्या",
        order_success: "ऑर्डर यशस्वी झाली!",

        // Product Details
        quantity: "प्रमाण",
        description: "माहिती",
        related_products: "संबंधित उत्पादने",
        product_details: "उत्पादनाची माहिती",
        offer: "ऑफर",
        product_desc_fallback: "ताज्या आणि उच्च गुणवत्तेच्या वस्तू थेट तुमच्या दारापर्यंत पोहोचवल्या जातात. स्थानिक शेतकऱ्यांकडून प्रमाणित।",
        "30_min": "30 मिनिटे",
        easy_return: "सुलभ परतावा",
        add_to_cart: "कार्टमध्ये जोडा",
        weight_g: "वजन (ग्रॅम)",
        price_rs: "किंमत (₹)",

        // Stock Status
        fresh: "ताजे",
        packet: "पॅकेट",
        shop_online: "ऑनलाइन",
        shop_offline: "ऑफलाइन",
        show_shop_to_customers: "ग्राहकांना दुकान दाखवा",

        // Auth
        login_desc: "तुमची ताजी खरेदी सुरू ठेवण्यासाठी लॉग इन करा।",
        select_shop: "दुकान निवडा",
        select_shop_desc: 'खरेदी सुरू ठेवण्यासाठी कृपया दुकान निवडा.',
        register_shop: 'तुमच्या दुकाची नोंदणी करा',
        register_shop_desc: 'तुमचे डिजिटल स्टोअरफ्रंट सेट करण्यासाठी फक्त एक मिनिट लागतो.',
        select_lang: 'पसंतीची भाषा निवडा',
        add_shop_image: 'दुकानाचा फोटो जोडा (पर्यायी)',
        change_image: 'फोटो बदला',
        shop_name: 'दुकानाचे नाव',
        shop_name_placeholder: 'उदा. जय मल्हार स्टोअर',
        shop_address: 'दुकानाचा पत्ता',
        shop_address_placeholder: 'पूर्ण पत्ता प्रविष्ट करा',
        fetch_location: 'लाइव्ह लोकेशन वापरा',
        create_store: 'माझे दुकान तयार करा',
        phone_number: "फोन नंबर",
        phone_placeholder: "तुमचा फोन नंबर टाका (उदा. 9876543210)",
        password_placeholder: "तुमचा पासवर्ड टाका",
        logging_in: "लॉग इन होत आहे...",
        no_account: "खाते नाही का?",
        signup: "साइन अप करा",
        login: "लॉग इन",
        join_fresh_club: "फ्रेश क्लबमध्ये सामील व्हा",
        signup_desc: "काही मिनिटांत ताज्या किराणा मालाची डिलिव्हरी तुमच्या घरी मिळवा।",
        full_name: "पूर्ण नाव",
        name_placeholder: "तुमचे नाव टाका",
        creating_account: "खाते तयार होत आहे...",
        create_account: "खाते तयार करा",
        already_have_account: "आधीच खाते आहे का?",
        by_signing_up: "साइन अप करून, तुम्ही आमच्या",
        terms_service: "सेवा अटी",
        and: "आणि",
        i_am_a: "मी एक...",
        customer: "ग्राहक",
        shopkeeper: "दुकानदार",

        // Onboarding
        onboard_title_1: "स्वागत आहे",
        onboard_desc_1: "तुमच्या दैनंदिन गरजा, तुमच्या विश्वसनीय स्थानिक किराणा दुकानातून ताज्या।",
        onboard_title_2: "सेंद्रिय डाळी",
        onboard_desc_2: "तुमच्या कुटुंबासाठी थेट सोर्र्स केलेल्या उच्च दर्जाच्या तूर, मूंग आणि मसूर डाळी।",
        onboard_title_3: "ताज्या भाज्या",
        onboard_desc_3: "शेत-ताज्या कांदा, बटाटे आणि टोमॅटो. दररोज हाताने निवडलेले।",
        onboard_title_4: "अस्सल मसाले",
        onboard_desc_4: "तुमच्या स्वयंपाकघरात भारताची खरी चव आणण्यासाठी शुद्ध हळद, मिरची आणि धणे।",

        // Orders
        my_orders: "माझे ऑर्डर",
        no_orders: "तुम्ही अजून कोणतीही ऑर्डर दिलेली नाही।",
        pending: "प्रलंबित",
        delivered: "पोहोचवले",
        cancelled: "रद्द",

        // Cart Empty
        cart_empty: "तुमची पिशवी रिकामी आहे",
        start_shopping: "खरेदी सुरू करा",
        clear: "साफ करा",
        subtotal: "उप-एकूण",
        proceed_to_buy: "खरेदीसाठी पुढे जा",
        placing_order: "ऑर्डर दिली जात आहे...",

        // Home Sections
        daily_use: "दररोजचा वापर",
        chai_nashta: "चहा आणि नाश्ता",
        spices_pulses: "मसाले आणि डाळी",
        household: "साफसफाई आणि घरगुती",
        pickup_from: "येथून पिकअप करा",

        // Showcase Items
        soft_drinks: "कोल्ड ड्रिंक्स",
        spices: "मसाले",
        cleaning: "साफसफाई",
        baby_care: "बेबी केअर",

        // Showcase Subtitles
        cool_fizzy: "थंड आणि ताजे",
        authentic_taste: "अस्सल चव",
        essentials: "अत्यावश्यक वस्तू",
        gentle_safe: "कोमल आणि सुरक्षित",

        // Showcase Tags
        upto_20_off: "20% पर्यंत सवलत",
        fresh_tag: "ताजे",
        best_seller: "सर्वात जास्त विक्री",
        trusted: "खात्रीशीर",

        // Extras
        unit: "नग",
        products: "उत्पाद",

        // Shopkeeper Common
        inventory: "इन्वेंटरी",
        shop_orders: "दुकानाचे ऑर्डर",
        credit: "उधारी",
        revenue: "एकूण कमाई",
        shop_performance: "दुकानाची कामगिरी",
        management: "व्यवस्थापन",

        // Shopkeeper Profile
        shopkeeper_profile: "दुकानदार प्रोफाइल",
        shop_owner: "दुकानाचे मालक",
        no_phone: "कोणताही फोन लिंक नाही",
        store_settings: "दुकानाच्या सेटिंग्ज",
        notifications: "सूचना",
        support_faq: "मदत आणि प्रश्न",
        switch_customer: "ग्राहक मोड",
        browse_as_user: "ग्राहक म्हणून पहा",
        shop_panel_v1: "दुकान पॅनेल v1.0.0",

        // Inventory
        weight_based: "वजन आधारित",
        packet_based: "पॅकेट आधारित",
        no_categories: "अद्याप कोणतीही श्रेणी नाही",
        tap_to_add_category: "पहिली श्रेणी जोडण्यासाठी + दाबा",
        delete_category: "श्रेणी हटवा",
        delete_category_confirm: "तुम्ही ही श्रेणी आणि त्यातील सर्व उत्पादने हटवू इच्छिता?",
        all_orders: "सर्व ऑर्डर",
        open: "खुले",
        completed: "पूर्ण झाले",
        add_to_credit: "उधारीत जोडा",
        mark_packed: "पॅक केले",
        ledger_updated: "खाते वही यशस्वीरित्या अद्यतनित केले",
        added_to_credit: "उधारीत जोडले!",
        credit_khata: "उधारी / खाते",
        total_due: "एकूण उधारी",
        add_customer: "नवीन ग्राहक जोडा",
        customer_name: "ग्राहकाचे नाव",
        initial_amount: "सुरुवातीची रक्कम (₹)",
        due: "बाकी",
        hidden: "लपवलेले",
        live: "सुरू",
        off: "बंद",
        selling_price: "विक्री किंमत (₹)",
        current_stock: "उपलब्ध स्टॉक",
        no_products: "अद्याप कोणतीही उत्पादने नाहीत",
        tap_to_add_product: "पहिले उत्पादन जोडण्यासाठी + दाबा",
        add_featured: "ताजे आगमन मध्ये जोडा",
        remove_featured: "ताजे आगमन मधून काढा",
        new_category: "नवीन कॅटेगरी",
        choose_icon: "अॅप्लिकेशन आयकॉन निवडा",
        upload_custom: "किंवा स्वतःचा फोटो लोड करा",
        upload_gallery: "गॅलरीतून अपलोड करा",
        category_name_label: "कॅटेगरीचे नाव",
        how_to_sell: "कॅटेगरीचा प्रकार (कसे विकायचे?)",
        weight_based_title: "वजनावर आधारित",
        item_based_title: "नगावर आधारित",
        create_category_btn: "कॅटेगरी तयार करा",
        add_item: "नवीन आयटम जोडा",
        tap_add_photo: "फोटो जोडण्यासाठी स्पर्श करा",
        product_name_label: "उत्पादनाचे नाव",
        subtitle_optional: "उप-शीर्षक (पर्यायी)",
        price_label: "किंमत (₹)",
        stock_label: "स्टॉक",
        show_in_featured: "ताजे आगमन मध्ये दाखवायचे?",
        featured_sub: "आयटम होम स्क्रीनच्या वरच्या भागात दिसतील.",
        save_product: "उत्पादन जतन करा",
    },
    hg: {
        // Common
        search: "Search karo",
        search_placeholder: "Category ya product dhoodho...",
        all_categories: "Saari Categories",
        explore_categories: "Category Explore karo",
        fresh_arrivals: "Naya maal",
        see_all: "Sab dekho",
        see_more: "Aur dekho",
        add: "ADD karo",
        out_of_stock: "Maal khatam",
        loading: "Ruko...",
        items: "items",
        gram: "gm",
        kg: "kg",
        pkt: "pkt",
        dozen: "dozen",

        // Tab Bar
        home: "Home",
        categories: "Categories",
        orders: "Orders",
        profile: "Profile",

        // Profile Screen
        my_profile: "Mera Profile",
        personal_info: "Meri Details",
        app_settings: "App Settings",
        language: "Language",
        select_language: "Language Chuno",
        switch_shopkeeper: "Dukandaar bano",
        logout: "Logout",
        help_support: "Madat chahiye?",
        privacy_policy: "Privacy Policy",
        balance: "Balance",
        delete_account: "Account Delete karo",
        delete_account_confirm: "Kya aap pakka account delete karna chahte ho? Ye wapas nahi aayega.",

        // Cart & Checkout
        my_cart: "Meri Cart",
        checkout: "Billing",
        total: "Total paisa",
        place_order: "Order dedo",
        order_success: "Order ho gaya!",

        // Product Details
        quantity: "Kitna chahiye",
        description: "Detail",
        related_products: "Aisa aur maal",
        product_details: "Product Details",
        offer: "OFFER",
        product_desc_fallback: "Fresh aur high quality products seedha aapke ghar tak. Local farmers se verified.",
        "30_min": "30 Min",
        easy_return: "Easy Return",
        add_to_cart: "Cart mein dalo",
        weight_g: "Wazan (g)",
        price_rs: "Price (₹)",

        // Stock Status
        fresh: "Taaza",
        packet: "Pocket",
        shop_online: "Online",
        shop_offline: "Offline",
        show_shop_to_customers: "Customers ko Shop dikhayein",

        // Auth
        login_desc: "Shopping continue karne ke liye login karo.",
        select_shop: "Shop Chuno",
        select_shop_desc: 'Shopping jaari rakhne ke liye ek shop chuno.',
        register_shop: 'Apni Shop Register Karen',
        register_shop_desc: 'Digital shop setup karne mein bas ek minute lagega.',
        select_lang: 'Apni pasandida Bhasha chunein',
        add_shop_image: 'Shop ki Image dalein (Optional)',
        change_image: 'Image badlein',
        shop_name: 'Shop ka Naam',
        shop_name_placeholder: 'e.g. Jai Malhar Store',
        shop_address: 'Shop ka Pata',
        shop_address_placeholder: 'Pura address daalein',
        fetch_location: 'Live Location use Karen',
        create_store: 'Meri Shop Banayein',
        phone_number: "Phone number",
        phone_placeholder: "Phone number dalo (jaise 9876543210)",
        password_placeholder: "Password dalo",
        logging_in: "Login ho raha hai...",
        no_account: "Account nahi hai?",
        signup: "Sign Up karo",
        login: "Login",
        join_fresh_club: "Fresh Club join karo",
        signup_desc: "Taaza rashan ghar bethe payein, bas kuch hi minutes mein.",
        full_name: "Pura Naam",
        name_placeholder: "Apna naam dalo",
        creating_account: "Account ban raha hai...",
        create_account: "Account banao",
        already_have_account: "Pehle se account hai?",
        by_signing_up: "Signup karke, aap humari",
        terms_service: "Terms of Service",
        and: "aur",
        i_am_a: "Mein hoon ek...",
        customer: "Grahak",
        shopkeeper: "Dukandaar",

        // Onboarding
        onboard_title_1: "Welcome",
        onboard_desc_1: "Aapki daily zarooratein, aapke bharosemand local Kirana store se taaza.",
        onboard_title_2: "Organic Daalein",
        onboard_desc_2: "High-quality Toor, Moong, aur Masoor Dal seedha aapki family ke liye.",
        onboard_title_3: "Taaza Sabziyan",
        onboard_desc_3: "Farm-fresh pyaz, aloo, aur tamatar. Rozana handpicked.",
        onboard_title_4: "Asli Masale",
        onboard_desc_4: "Shuddh Haldi, Mirchi, aur Dhania India ka asli swad aapki kitchen mein.",

        // Orders
        my_orders: "Mere Orders",
        no_orders: "Aapne abhi tak koi order nahi diya.",
        pending: "Pending",
        delivered: "Aa gaya",
        cancelled: "Cancel ho gaya",

        // Cart Empty
        cart_empty: "Aapki cart khali hai",
        start_shopping: "Shopping shuru karo",
        clear: "Saaf karo",
        subtotal: "Subtotal",
        proceed_to_buy: "Kharidne ke liye aage badho",
        placing_order: "Order ja raha hai...",

        // Home Sections
        daily_use: "Daily Use ka saman",
        chai_nashta: "Chai & Nashta",
        spices_pulses: "Masale aur Daalein",
        household: "Safi aur Ghar ka saman",
        pickup_from: "Yahan se le lo",

        // Showcase Items
        soft_drinks: "Cold Drinks",
        spices: "Masale",
        cleaning: "Cleaning",
        baby_care: "Baby Care",

        // Showcase Subtitles
        cool_fizzy: "Thanda aur Fizzy",
        authentic_taste: "Asli Swad",
        essentials: "Zaroori Saman",
        gentle_safe: "Soft aur Safe",

        // Showcase Tags
        upto_20_off: "Upto 20% OFF",
        fresh_tag: "Taaza",
        best_seller: "Sabse zyada bikne wala",
        trusted: "Sahi hai",

        // Extras
        unit: "unit",
        products: "Products",

        // Shopkeeper Common
        inventory: "Inventory",
        shop_orders: "Shop Orders",
        credit: "Credit / Udhaari",
        revenue: "Kamaai",
        shop_performance: "Dukan ki Performance",
        management: "Management",

        // Shopkeeper Profile
        shopkeeper_profile: "Dukandaar Profile",
        shop_owner: "Dukan ke malik",
        no_phone: "Phone link nahi hai",
        store_settings: "Dukan Settings",
        notifications: "Notifications",
        support_faq: "Madat aur Sawal",
        switch_customer: "Grahak bano",
        browse_as_user: "User jaise dekho",
        shop_panel_v1: "Shop Panel v1.0.0",

        // Inventory
        weight_based: "Wazan wala",
        packet_based: "Packet wala",
        no_categories: "Koi category nahi hai",
        tap_to_add_category: "Nayi category ke liye + dabao",
        delete_category: "Category hatao",
        delete_category_confirm: "Kya aap ye category aur iske saare products hatana chahte hain?",
        all_orders: "Saare Orders",
        open: "Open",
        completed: "Pura ho gaya",
        add_to_credit: "Udhaari mein dalo",
        mark_packed: "Pack ho gaya",
        ledger_updated: "Khata update ho gaya",
        added_to_credit: "Udhaari mein add ho gaya!",
        credit_khata: "Credit / Khata",
        total_due: "Total Udhaari",
        add_customer: "Naya Grahak banao",
        customer_name: "Grahak ka Naam",
        initial_amount: "Shuruat ka Paisa (₹)",
        due: "Baaki",
        hidden: "Hidden",
        live: "Live",
        off: "Off",
        selling_price: "Selling Price (₹)",
        current_stock: "Current Stock",
        no_products: "Abhi koi product nahi hai",
        tap_to_add_product: "Naya product banane ke liye + dabao",
        add_featured: "Fresh Arrivals mein dalo",
        remove_featured: "Fresh Arrivals se hatao",
        new_category: "Nayi Category",
        choose_icon: "Application Icon select karo",
        upload_custom: "YA KHUD KA PHOTO BHEJO",
        upload_gallery: "Gallery se upload karo",
        category_name_label: "Category ka Naam",
        how_to_sell: "Category Type (Kaise bechna hai?)",
        weight_based_title: "Wazan ke hisab se",
        item_based_title: "Nag ke hisab se",
        create_category_btn: "Category Banao",
        add_item: "Item Add Karo",
        tap_add_photo: "Photo lagane ke liye touch karo",
        product_name_label: "Product ka Naam",
        subtitle_optional: "Subtitle (Jaruri nahi hai)",
        price_label: "Price (₹)",
        stock_label: "Stock",
        show_in_featured: "Fresh Arrivals mein dikhana hai?",
        featured_sub: "Items Home Screen ke top section mein dikhenge.",
        save_product: "Product Save Karo",
    }
};
